# Generated by Django 5.1.7 on 2025-04-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_gst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_tin_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
