# Generated by Django 5.1.7 on 2025-04-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0002_invoice_shipping_address_invoice_shipping_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_gst',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_phone',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_tin_number',
        ),
    ]
