# Generated by Django 5.1.7 on 2025-04-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0003_remove_invoice_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='account_type',
            field=models.CharField(blank=True, choices=[('savings', 'Savings Account'), ('current', 'Current Account'), ('salary', 'Salary Account'), ('fixed_deposit', 'Fixed Deposit Account'), ('recurring_deposit', 'Recurring Deposit Account'), ('nro', 'NRO Account'), ('nre', 'NRE Account'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
