# Generated by Django 5.1.7 on 2025-04-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0004_bankdetails_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_pan',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
