# Generated by Django 5.1.7 on 2026-02-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0005_customer_customer_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
