# Generated by Django 5.1.7 on 2026-06-16 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0006_invoice_project_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.IntegerField()),
                ('credit_note_date', models.DateField()),
                ('credit_note_customer_gst', models.CharField(blank=True, max_length=15, null=True)),
                ('credit_note_customer_phone', models.CharField(blank=True, max_length=14, null=True)),
                ('credit_note_amt_without_gst', models.FloatField()),
                ('credit_note_amt_igst', models.FloatField()),
                ('credit_note_amt_cgst', models.FloatField()),
                ('credit_note_amt_sgst', models.FloatField()),
                ('credit_note_amt_with_gst', models.FloatField()),
                ('credit_note_json', models.TextField()),
                ('buyer_tin_number', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, default=None, null=True)),
                ('business_tin_number', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('sup_pan_number', models.CharField(blank=True, default=0, max_length=15, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('associated_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='gstbillingapp.invoice')),
                ('bank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gstbillingapp.bankdetails')),
                ('credit_note_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gstbillingapp.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
